### ISSUE TITLE
[ethjs-query] while formatting inputs ... Error: [ethjs-format] hex string ... must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 54 bytes

### ISSUE THREAD

**Issue by 1blockologist** [vanbexlabs/ethereum-auth-demo#1]
It doesn't matter if this is ropsten testnet or mainnet, I get an error with whatever address I have unlocked in Metamask

 Error: [ethjs-query] while formatting inputs '["0x1cd35769e5e5e03493dc532bddd0d94f5a8723b2","0x5369676e20696e746f20687474703a2f2f6c6f63616c686f7374"]' for method 'personal_sign' error: Error: [ethjs-format] hex string '0x5369676e20696e746f20687474703a2f2f6c6f63616c686f7374' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 54 bytes

I dived into this error message on the ethjs and metamask github pages but was inconclusive. It may be related to a deeper error about having too many event watchers open

Any thoughts?

**Comment by wl-tsui** [comment]
Yeah how did you solve this? thk~

**Comment by jackynguyen93** [comment]
I got the same error

**Comment by vasa-develop** [comment]
@dwardu I tried it out with the updates web3-auth. But it still throws the same error.

**Comment by 1blockologist** [comment]
@vasa-develop this repo is just very out of date, I’m closing this issue as I have a functioning dapp now and cant pinpoint exactly what I did to get past this block in my understanding 10 months ago
